'use strict';

const error = require('throw.js');



/**
 * Creates a new invoice
 * @param {String} invoice Member identifier
 * @throws {InternalServerError} When there's an unexpected error.
 */
module.exports.create = async (invoice) => {
    try {

    }
    catch (err) {
        throw err;
    }
};